/*
Navicat Oracle Data Transfer
Oracle Client Version : 11.2.0.3.0

Source Server         : Oracle
Source Server Version : 110200
Source Host           : 127.0.0.1:1521
Source Schema         : SHAREDCLOUD

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2017-06-23 23:45:41 
*/


-- ----------------------------
-- Table structure for ADM
-- ----------------------------
DROP TABLE "SHAREDCLOUD"."ADM";
CREATE TABLE "SHAREDCLOUD"."ADM" (
"ADMID" VARCHAR2(36 BYTE) NOT NULL ,
"EMAIL" VARCHAR2(30 BYTE) NOT NULL ,
"PASSWORD" VARCHAR2(40 BYTE) NOT NULL ,
"STATUS" NUMBER(2) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of ADM
-- ----------------------------

-- ----------------------------
-- Table structure for DOWNLOAD_HISTORY
-- ----------------------------
DROP TABLE "SHAREDCLOUD"."DOWNLOAD_HISTORY";
CREATE TABLE "SHAREDCLOUD"."DOWNLOAD_HISTORY" (
"ID" VARCHAR2(36 BYTE) NOT NULL ,
"USERID" VARCHAR2(36 BYTE) NOT NULL ,
"FILEID" VARCHAR2(36 BYTE) NOT NULL ,
"DOWNLOADTIME" TIMESTAMP(6)  NOT NULL ,
"STATUS" NUMBER(2) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of DOWNLOAD_HISTORY
-- ----------------------------

-- ----------------------------
-- Table structure for FILES
-- ----------------------------
DROP TABLE "SHAREDCLOUD"."FILES";
CREATE TABLE "SHAREDCLOUD"."FILES" (
"FILEID" VARCHAR2(36 BYTE) NOT NULL ,
"FILESIZE" FLOAT(63) NOT NULL ,
"FILEPATH" VARCHAR2(100 BYTE) NULL ,
"STATUS" NUMBER(2) NOT NULL ,
"ISDIR" NUMBER(2) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of FILES
-- ----------------------------
INSERT INTO "SHAREDCLOUD"."FILES" VALUES ('4e4fec8b-053c-44e0-a2b0-d1a724b0061c', '5199312', '4e4fec8b-053c-44e0-a2b0-d1a724b0061c.png', '1', '-1');
INSERT INTO "SHAREDCLOUD"."FILES" VALUES ('6536ada2-7321-4c17-82ec-955da1b2d1bb', '5384332', '6536ada2-7321-4c17-82ec-955da1b2d1bb.png', '1', '-1');
INSERT INTO "SHAREDCLOUD"."FILES" VALUES ('1661c985-0e91-41cc-9e0f-25696bb258c2', '-1', null, '1', '1');

-- ----------------------------
-- Table structure for FILES_MAG_LOG
-- ----------------------------
DROP TABLE "SHAREDCLOUD"."FILES_MAG_LOG";
CREATE TABLE "SHAREDCLOUD"."FILES_MAG_LOG" (
"ID" VARCHAR2(36 BYTE) NOT NULL ,
"FILEID" VARCHAR2(36 BYTE) NOT NULL ,
"ADMID" VARCHAR2(36 BYTE) NOT NULL ,
"OPERATION" VARCHAR2(10 BYTE) NOT NULL ,
"STATUS" NUMBER(2) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of FILES_MAG_LOG
-- ----------------------------

-- ----------------------------
-- Table structure for SHAREDFILES
-- ----------------------------
DROP TABLE "SHAREDCLOUD"."SHAREDFILES";
CREATE TABLE "SHAREDCLOUD"."SHAREDFILES" (
"SHAREDFILEID" VARCHAR2(36 BYTE) NOT NULL ,
"USERID" VARCHAR2(36 BYTE) NOT NULL ,
"UPLOADHISTORYID" VARCHAR2(36 BYTE) NULL ,
"ISPUBLIC" NUMBER(1) NOT NULL ,
"PASSWORD" VARCHAR2(10 BYTE) NULL ,
"SHAREDTIME" TIMESTAMP(6)  NOT NULL ,
"DOWNLOADNUMBER" FLOAT(63) NOT NULL ,
"BROWSENUMBER" FLOAT(63) NOT NULL ,
"SAVENUMBER" FLOAT(63) NOT NULL ,
"STATUS" NUMBER(2) NOT NULL ,
"FILEID" VARCHAR2(36 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of SHAREDFILES
-- ----------------------------
INSERT INTO "SHAREDCLOUD"."SHAREDFILES" VALUES ('c82a9836-96ab-40b6-9f02-eeca8ef40cc3', 'ddf4122e-1d2d-4059-83dc-fd7f90ceaa94', '097674ac-4de1-42ed-9e37-63cf26d8977c', '1', null, TO_TIMESTAMP(' 2017-06-23 23:44:45:903000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '0', '0', '0', '1', null);
INSERT INTO "SHAREDCLOUD"."SHAREDFILES" VALUES ('a910b33c-b5ae-4b26-85a8-7a45926e7351', 'ddf4122e-1d2d-4059-83dc-fd7f90ceaa94', '7179d495-228b-4110-be6f-e5f2b542dfec', '1', null, TO_TIMESTAMP(' 2017-06-23 23:42:08:751000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '0', '0', '0', '1', null);

-- ----------------------------
-- Table structure for SHAREDFILES_MAG_LOG
-- ----------------------------
DROP TABLE "SHAREDCLOUD"."SHAREDFILES_MAG_LOG";
CREATE TABLE "SHAREDCLOUD"."SHAREDFILES_MAG_LOG" (
"ID" VARCHAR2(36 BYTE) NOT NULL ,
"SHAREDFILEID" VARCHAR2(36 BYTE) NOT NULL ,
"ADMID" VARCHAR2(36 BYTE) NOT NULL ,
"OPERATION" VARCHAR2(10 BYTE) NOT NULL ,
"STATUS" NUMBER(2) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of SHAREDFILES_MAG_LOG
-- ----------------------------

-- ----------------------------
-- Table structure for UPLOAD_HISTORY
-- ----------------------------
DROP TABLE "SHAREDCLOUD"."UPLOAD_HISTORY";
CREATE TABLE "SHAREDCLOUD"."UPLOAD_HISTORY" (
"ID" VARCHAR2(36 BYTE) NOT NULL ,
"USERID" VARCHAR2(36 BYTE) NOT NULL ,
"FILEID" VARCHAR2(36 BYTE) NOT NULL ,
"UPLOADTIME" TIMESTAMP(6)  NOT NULL ,
"STATUS" NUMBER(2) NOT NULL ,
"FILENAME" VARCHAR2(100 BYTE) NOT NULL ,
"PID" VARCHAR2(36 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of UPLOAD_HISTORY
-- ----------------------------
INSERT INTO "SHAREDCLOUD"."UPLOAD_HISTORY" VALUES ('50917a05-b65a-4535-8c75-59698e17c24c', 'ddf4122e-1d2d-4059-83dc-fd7f90ceaa94', '1661c985-0e91-41cc-9e0f-25696bb258c2', TO_TIMESTAMP(' 2017-06-23 23:34:45:493000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1', '囧', null);
INSERT INTO "SHAREDCLOUD"."UPLOAD_HISTORY" VALUES ('7179d495-228b-4110-be6f-e5f2b542dfec', 'ddf4122e-1d2d-4059-83dc-fd7f90ceaa94', '6536ada2-7321-4c17-82ec-955da1b2d1bb', TO_TIMESTAMP(' 2017-06-23 23:39:23:428000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1', 'TERA_ScreenShot_20170410_101016.png', '50917a05-b65a-4535-8c75-59698e17c24c');
INSERT INTO "SHAREDCLOUD"."UPLOAD_HISTORY" VALUES ('097674ac-4de1-42ed-9e37-63cf26d8977c', 'ddf4122e-1d2d-4059-83dc-fd7f90ceaa94', '4e4fec8b-053c-44e0-a2b0-d1a724b0061c', TO_TIMESTAMP(' 2017-06-23 23:39:07:934000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1', 'TERA_ScreenShot_20170410_101412.png', null);

-- ----------------------------
-- Table structure for UPLOAD_HISTORY_MAG_LOG
-- ----------------------------
DROP TABLE "SHAREDCLOUD"."UPLOAD_HISTORY_MAG_LOG";
CREATE TABLE "SHAREDCLOUD"."UPLOAD_HISTORY_MAG_LOG" (
"ID" VARCHAR2(36 BYTE) NOT NULL ,
"UPLOADHISTORYID" VARCHAR2(36 BYTE) NOT NULL ,
"ADMID" VARCHAR2(36 BYTE) NOT NULL ,
"STATUS" NUMBER(2) NOT NULL ,
"OPERATION" VARCHAR2(10 BYTE) NOT NULL ,
"UPLOAD_HISTORY_ID" VARCHAR2(36 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of UPLOAD_HISTORY_MAG_LOG
-- ----------------------------

-- ----------------------------
-- Table structure for UPLOADHISTORY_MAG_LOG
-- ----------------------------
DROP TABLE "SHAREDCLOUD"."UPLOADHISTORY_MAG_LOG";
CREATE TABLE "SHAREDCLOUD"."UPLOADHISTORY_MAG_LOG" (
"ID" VARCHAR2(36 BYTE) NOT NULL ,
"UPLOAD_HISTORY_ID" VARCHAR2(36 BYTE) NOT NULL ,
"ADMID" VARCHAR2(36 BYTE) NOT NULL ,
"OPERATION" VARCHAR2(10 BYTE) NOT NULL ,
"STATUS" NUMBER(3) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of UPLOADHISTORY_MAG_LOG
-- ----------------------------

-- ----------------------------
-- Table structure for USERS
-- ----------------------------
DROP TABLE "SHAREDCLOUD"."USERS";
CREATE TABLE "SHAREDCLOUD"."USERS" (
"USERID" VARCHAR2(36 BYTE) NOT NULL ,
"EMAIL" VARCHAR2(30 BYTE) NOT NULL ,
"PASSWORD" VARCHAR2(40 BYTE) NOT NULL ,
"USERNAME" VARCHAR2(25 BYTE) NOT NULL ,
"BIRTHDAY" DATE NOT NULL ,
"AGE" NUMBER(3) NOT NULL ,
"SEX" VARCHAR2(10 BYTE) NOT NULL ,
"SAVEDFILESIZE" FLOAT(63) NOT NULL ,
"TOTALFILESIZE" FLOAT(63) NOT NULL ,
"STATUS" NUMBER(2) NOT NULL ,
"REGISTTIME" TIMESTAMP(6)  NOT NULL ,
"ACTIVITYTIME" TIMESTAMP(6)  NOT NULL ,
"ACTIVITYCODE" VARCHAR2(36 BYTE) NOT NULL ,
"INTRO" VARCHAR2(255 BYTE) NULL ,
"UPDATEPWDVERIFYCODE" VARCHAR2(36 BYTE) NULL ,
"HEADIMGPATH" VARCHAR2(50 BYTE) NULL ,
"UPDATEPWDREQSUBMITTIME" TIMESTAMP(6)  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of USERS
-- ----------------------------
INSERT INTO "SHAREDCLOUD"."USERS" VALUES ('3696d807-67eb-492f-bd0a-d8c75ca701ac', '666666@qq.com', '00475e1c169583ae78c80d2ed7701e14', '张大可', TO_DATE('1995-01-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '22', '未知', '1200247259', '1099511627776', '1', TO_TIMESTAMP(' 2017-01-12 08:29:21:878000', 'YYYY-MM-DD HH24:MI:SS:FF6'), TO_TIMESTAMP(' 2017-01-12 08:29:21:878000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'cc08543f-214d-4225-a5e0-bb65ea6add27', '我的电脑，时尚时尚，最时尚，敲代码肯定棒', '3c04e516-2d08-4ffb-84c8-0bbd31aaae3e', null, TO_TIMESTAMP(' 2017-01-12 11:20:24:216000', 'YYYY-MM-DD HH24:MI:SS:FF6'));
INSERT INTO "SHAREDCLOUD"."USERS" VALUES ('ddf4122e-1d2d-4059-83dc-fd7f90ceaa94', '1213840358@qq.com', '25d55ad283aa400af464c76d713c07ad', 'zx', TO_DATE('1995-12-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '22', '男', '10583644', '1099511627776', '1', TO_TIMESTAMP(' 2017-06-23 23:32:43:976000', 'YYYY-MM-DD HH24:MI:SS:FF6'), TO_TIMESTAMP(' 2017-06-23 23:32:43:976000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '9b7ba9ad-1d5f-4b0e-8b64-19a0b2b25b28', '4654654', null, null, null);

-- ----------------------------
-- Table structure for USERS_MAG_LOG
-- ----------------------------
DROP TABLE "SHAREDCLOUD"."USERS_MAG_LOG";
CREATE TABLE "SHAREDCLOUD"."USERS_MAG_LOG" (
"ID" VARCHAR2(36 BYTE) NOT NULL ,
"USERID" VARCHAR2(36 BYTE) NOT NULL ,
"ADMID" VARCHAR2(36 BYTE) NOT NULL ,
"OPERATION" VARCHAR2(10 BYTE) NOT NULL ,
"STATUS" NUMBER(2) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of USERS_MAG_LOG
-- ----------------------------

-- ----------------------------
-- Function structure for GETFILENAMEEXT
-- ----------------------------
CREATE OR REPLACE FUNCTION "SHAREDCLOUD"."GETFILENAMEEXT"(fileName IN VARCHAR2 DEFAULT '')
RETURN VARCHAR2
AS
	var_ext varchar2(255):='';
	var_tempExt varchar2(255):='';
BEGIN
	var_tempExt:= SUBSTR(fileName,INSTR(fileName, '.', -1)+1,LENGTH(fileName));
	IF var_tempExt=fileName THEN
		var_ext:='';
	ELSE 
		var_ext:=var_tempExt;
	END IF;
	DBMS_OUTPUT.PUT_LINE('as');
	return lower(var_ext);
END;




/

-- ----------------------------
-- Function structure for ISMATCHEXT
-- ----------------------------
CREATE OR REPLACE FUNCTION "SHAREDCLOUD"."ISMATCHEXT"(param_ext IN VARCHAR2 DEFAULT '', param_exts IN VARCHAR2 DEFAULT '')
RETURN int
AS
	var_leftChar VARCHAR2(1):='';
	var_rightChar VARCHAR2(1):='';
	var_isMatch int:=0;
	var_matchPosition NUMBER:=-1;
	var_ext VARCHAR2(255):=lower(param_ext);
	var_exts VARCHAR2(255):=lower(param_exts);
BEGIN
	--判断需要判断的后缀是否存在违规字符
	IF INSTR(var_ext,',')>0 THEN
		RETURN var_isMatch;
	END IF;
	--判断子字符串所在位置
	var_matchPosition := INSTR(var_exts, var_ext);
	--判断是否为第一个字符
	IF	var_matchPosition>1 THEN
		
		var_leftChar:=SUBSTR(var_exts, var_matchPosition-1, 1);
	ELSE 
		var_leftChar:=',';
	END IF;
	--判断是否为最后一个字符
	IF	var_matchPosition+LENGTH(var_ext)<LENGTH(var_exts) THEN
		
		var_rightChar:=SUBSTR(var_exts, var_matchPosition+LENGTH(var_ext), 1);
	ELSE 
		var_rightChar:=',';
	END IF;

	
	DBMS_OUTPUT.PUT_LINE(var_matchPosition);
	DBMS_OUTPUT.PUT_LINE(var_leftChar);
	DBMS_OUTPUT.PUT_LINE(var_rightChar);
	IF var_matchPosition>0 AND var_leftChar=',' and var_rightChar=',' THEN
		var_isMatch:=1;
	END IF;
	RETURN var_isMatch;
END;

/

-- ----------------------------
-- Indexes structure for table ADM
-- ----------------------------

-- ----------------------------
-- Uniques structure for table ADM
-- ----------------------------
ALTER TABLE "SHAREDCLOUD"."ADM" ADD UNIQUE ("EMAIL");

-- ----------------------------
-- Checks structure for table ADM
-- ----------------------------
ALTER TABLE "SHAREDCLOUD"."ADM" ADD CHECK ("ADMID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."ADM" ADD CHECK ("EMAIL" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."ADM" ADD CHECK ("PASSWORD" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."ADM" ADD CHECK ("STATUS" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."ADM" ADD CHECK ("EMAIL" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."ADM" ADD CHECK ("PASSWORD" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."ADM" ADD CHECK ("STATUS" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."ADM" ADD CHECK ("EMAIL" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."ADM" ADD CHECK ("PASSWORD" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."ADM" ADD CHECK ("STATUS" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."ADM" ADD CHECK ("EMAIL" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."ADM" ADD CHECK ("PASSWORD" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."ADM" ADD CHECK ("STATUS" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table ADM
-- ----------------------------
ALTER TABLE "SHAREDCLOUD"."ADM" ADD PRIMARY KEY ("ADMID");

-- ----------------------------
-- Indexes structure for table DOWNLOAD_HISTORY
-- ----------------------------

-- ----------------------------
-- Checks structure for table DOWNLOAD_HISTORY
-- ----------------------------
ALTER TABLE "SHAREDCLOUD"."DOWNLOAD_HISTORY" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."DOWNLOAD_HISTORY" ADD CHECK ("USERID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."DOWNLOAD_HISTORY" ADD CHECK ("FILEID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."DOWNLOAD_HISTORY" ADD CHECK ("DOWNLOADTIME" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."DOWNLOAD_HISTORY" ADD CHECK ("STATUS" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."DOWNLOAD_HISTORY" ADD CHECK ("USERID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."DOWNLOAD_HISTORY" ADD CHECK ("FILEID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."DOWNLOAD_HISTORY" ADD CHECK ("DOWNLOADTIME" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."DOWNLOAD_HISTORY" ADD CHECK ("STATUS" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table DOWNLOAD_HISTORY
-- ----------------------------
ALTER TABLE "SHAREDCLOUD"."DOWNLOAD_HISTORY" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FILES
-- ----------------------------

-- ----------------------------
-- Checks structure for table FILES
-- ----------------------------
ALTER TABLE "SHAREDCLOUD"."FILES" ADD CHECK ("FILEID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."FILES" ADD CHECK ("FILESIZE" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."FILES" ADD CHECK ("STATUS" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."FILES" ADD CHECK ("ISDIR" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."FILES" ADD CHECK ("STATUS" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."FILES" ADD CHECK ("ISDIR" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."FILES" ADD CHECK ("FILESIZE" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."FILES" ADD CHECK ("STATUS" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."FILES" ADD CHECK ("ISDIR" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."FILES" ADD CHECK ("FILESIZE" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."FILES" ADD CHECK ("STATUS" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."FILES" ADD CHECK ("ISDIR" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."FILES" ADD CHECK ("FILESIZE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FILES
-- ----------------------------
ALTER TABLE "SHAREDCLOUD"."FILES" ADD PRIMARY KEY ("FILEID");

-- ----------------------------
-- Indexes structure for table FILES_MAG_LOG
-- ----------------------------

-- ----------------------------
-- Checks structure for table FILES_MAG_LOG
-- ----------------------------
ALTER TABLE "SHAREDCLOUD"."FILES_MAG_LOG" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."FILES_MAG_LOG" ADD CHECK ("FILEID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."FILES_MAG_LOG" ADD CHECK ("ADMID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."FILES_MAG_LOG" ADD CHECK ("OPERATION" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."FILES_MAG_LOG" ADD CHECK ("STATUS" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."FILES_MAG_LOG" ADD CHECK ("FILEID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."FILES_MAG_LOG" ADD CHECK ("ADMID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."FILES_MAG_LOG" ADD CHECK ("OPERATION" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."FILES_MAG_LOG" ADD CHECK ("STATUS" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FILES_MAG_LOG
-- ----------------------------
ALTER TABLE "SHAREDCLOUD"."FILES_MAG_LOG" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table SHAREDFILES
-- ----------------------------

-- ----------------------------
-- Checks structure for table SHAREDFILES
-- ----------------------------
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES" ADD CHECK ("SHAREDFILEID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES" ADD CHECK ("USERID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES" ADD CHECK ("ISPUBLIC" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES" ADD CHECK ("SHAREDTIME" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES" ADD CHECK ("DOWNLOADNUMBER" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES" ADD CHECK ("BROWSENUMBER" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES" ADD CHECK ("SAVENUMBER" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES" ADD CHECK ("STATUS" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES" ADD CHECK ("USERID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES" ADD CHECK ("ISPUBLIC" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES" ADD CHECK ("SHAREDTIME" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES" ADD CHECK ("DOWNLOADNUMBER" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES" ADD CHECK ("BROWSENUMBER" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES" ADD CHECK ("SAVENUMBER" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES" ADD CHECK ("STATUS" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES" ADD CHECK ("USERID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES" ADD CHECK ("ISPUBLIC" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES" ADD CHECK ("SHAREDTIME" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES" ADD CHECK ("DOWNLOADNUMBER" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES" ADD CHECK ("BROWSENUMBER" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES" ADD CHECK ("SAVENUMBER" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES" ADD CHECK ("STATUS" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES" ADD CHECK ("USERID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES" ADD CHECK ("ISPUBLIC" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES" ADD CHECK ("SHAREDTIME" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES" ADD CHECK ("DOWNLOADNUMBER" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES" ADD CHECK ("BROWSENUMBER" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES" ADD CHECK ("SAVENUMBER" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES" ADD CHECK ("STATUS" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SHAREDFILES
-- ----------------------------
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES" ADD PRIMARY KEY ("SHAREDFILEID");

-- ----------------------------
-- Indexes structure for table SHAREDFILES_MAG_LOG
-- ----------------------------

-- ----------------------------
-- Checks structure for table SHAREDFILES_MAG_LOG
-- ----------------------------
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES_MAG_LOG" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES_MAG_LOG" ADD CHECK ("SHAREDFILEID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES_MAG_LOG" ADD CHECK ("ADMID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES_MAG_LOG" ADD CHECK ("OPERATION" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES_MAG_LOG" ADD CHECK ("STATUS" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES_MAG_LOG" ADD CHECK ("SHAREDFILEID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES_MAG_LOG" ADD CHECK ("ADMID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES_MAG_LOG" ADD CHECK ("OPERATION" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES_MAG_LOG" ADD CHECK ("STATUS" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SHAREDFILES_MAG_LOG
-- ----------------------------
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES_MAG_LOG" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table UPLOAD_HISTORY
-- ----------------------------

-- ----------------------------
-- Checks structure for table UPLOAD_HISTORY
-- ----------------------------
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY" ADD CHECK ("USERID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY" ADD CHECK ("FILEID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY" ADD CHECK ("UPLOADTIME" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY" ADD CHECK ("STATUS" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY" ADD CHECK ("FILENAME" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY" ADD CHECK ("USERID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY" ADD CHECK ("FILEID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY" ADD CHECK ("UPLOADTIME" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY" ADD CHECK ("STATUS" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY" ADD CHECK ("FILENAME" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY" ADD CHECK ("USERID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY" ADD CHECK ("FILEID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY" ADD CHECK ("UPLOADTIME" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY" ADD CHECK ("STATUS" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY" ADD CHECK ("FILENAME" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY" ADD CHECK ("USERID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY" ADD CHECK ("FILEID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY" ADD CHECK ("UPLOADTIME" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY" ADD CHECK ("STATUS" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY" ADD CHECK ("FILENAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table UPLOAD_HISTORY
-- ----------------------------
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table UPLOAD_HISTORY_MAG_LOG
-- ----------------------------

-- ----------------------------
-- Checks structure for table UPLOAD_HISTORY_MAG_LOG
-- ----------------------------
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY_MAG_LOG" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY_MAG_LOG" ADD CHECK ("UPLOADHISTORYID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY_MAG_LOG" ADD CHECK ("ADMID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY_MAG_LOG" ADD CHECK ("STATUS" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY_MAG_LOG" ADD CHECK ("OPERATION" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY_MAG_LOG" ADD CHECK ("UPLOAD_HISTORY_ID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY_MAG_LOG" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY_MAG_LOG" ADD CHECK ("UPLOADHISTORYID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY_MAG_LOG" ADD CHECK ("ADMID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY_MAG_LOG" ADD CHECK ("STATUS" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY_MAG_LOG" ADD CHECK ("OPERATION" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY_MAG_LOG" ADD CHECK ("UPLOAD_HISTORY_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table UPLOAD_HISTORY_MAG_LOG
-- ----------------------------
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY_MAG_LOG" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table UPLOADHISTORY_MAG_LOG
-- ----------------------------

-- ----------------------------
-- Checks structure for table UPLOADHISTORY_MAG_LOG
-- ----------------------------
ALTER TABLE "SHAREDCLOUD"."UPLOADHISTORY_MAG_LOG" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."UPLOADHISTORY_MAG_LOG" ADD CHECK ("UPLOAD_HISTORY_ID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."UPLOADHISTORY_MAG_LOG" ADD CHECK ("ADMID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."UPLOADHISTORY_MAG_LOG" ADD CHECK ("OPERATION" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."UPLOADHISTORY_MAG_LOG" ADD CHECK ("STATUS" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table UPLOADHISTORY_MAG_LOG
-- ----------------------------
ALTER TABLE "SHAREDCLOUD"."UPLOADHISTORY_MAG_LOG" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table USERS
-- ----------------------------

-- ----------------------------
-- Uniques structure for table USERS
-- ----------------------------
ALTER TABLE "SHAREDCLOUD"."USERS" ADD UNIQUE ("EMAIL");
ALTER TABLE "SHAREDCLOUD"."USERS" ADD UNIQUE ("USERNAME");

-- ----------------------------
-- Checks structure for table USERS
-- ----------------------------
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("USERID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("EMAIL" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("PASSWORD" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("USERNAME" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("BIRTHDAY" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("AGE" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("SEX" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("SAVEDFILESIZE" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("TOTALFILESIZE" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("STATUS" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("REGISTTIME" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("ACTIVITYTIME" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("ACTIVITYCODE" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("EMAIL" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("PASSWORD" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("USERNAME" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("BIRTHDAY" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("AGE" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("SEX" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("SAVEDFILESIZE" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("TOTALFILESIZE" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("STATUS" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("REGISTTIME" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("ACTIVITYTIME" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("ACTIVITYCODE" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("EMAIL" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("PASSWORD" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("USERNAME" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("BIRTHDAY" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("AGE" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("SEX" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("SAVEDFILESIZE" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("TOTALFILESIZE" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("STATUS" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("REGISTTIME" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("ACTIVITYTIME" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("ACTIVITYCODE" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("EMAIL" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("PASSWORD" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("USERNAME" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("BIRTHDAY" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("AGE" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("SEX" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("SAVEDFILESIZE" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("TOTALFILESIZE" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("STATUS" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("REGISTTIME" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("ACTIVITYTIME" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS" ADD CHECK ("ACTIVITYCODE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table USERS
-- ----------------------------
ALTER TABLE "SHAREDCLOUD"."USERS" ADD PRIMARY KEY ("USERID");

-- ----------------------------
-- Checks structure for table USERS_MAG_LOG
-- ----------------------------
ALTER TABLE "SHAREDCLOUD"."USERS_MAG_LOG" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS_MAG_LOG" ADD CHECK ("USERID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS_MAG_LOG" ADD CHECK ("ADMID" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS_MAG_LOG" ADD CHECK ("OPERATION" IS NOT NULL);
ALTER TABLE "SHAREDCLOUD"."USERS_MAG_LOG" ADD CHECK ("STATUS" IS NOT NULL);

-- ----------------------------
-- Foreign Key structure for table "SHAREDCLOUD"."DOWNLOAD_HISTORY"
-- ----------------------------
ALTER TABLE "SHAREDCLOUD"."DOWNLOAD_HISTORY" ADD FOREIGN KEY ("FILEID") REFERENCES "SHAREDCLOUD"."FILES" ("FILEID");
ALTER TABLE "SHAREDCLOUD"."DOWNLOAD_HISTORY" ADD FOREIGN KEY ("USERID") REFERENCES "SHAREDCLOUD"."USERS" ("USERID");

-- ----------------------------
-- Foreign Key structure for table "SHAREDCLOUD"."FILES_MAG_LOG"
-- ----------------------------
ALTER TABLE "SHAREDCLOUD"."FILES_MAG_LOG" ADD FOREIGN KEY ("ADMID") REFERENCES "SHAREDCLOUD"."ADM" ("ADMID");
ALTER TABLE "SHAREDCLOUD"."FILES_MAG_LOG" ADD FOREIGN KEY ("FILEID") REFERENCES "SHAREDCLOUD"."FILES" ("FILEID");

-- ----------------------------
-- Foreign Key structure for table "SHAREDCLOUD"."SHAREDFILES"
-- ----------------------------
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES" ADD FOREIGN KEY ("FILEID") REFERENCES "SHAREDCLOUD"."FILES" ("FILEID");
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES" ADD FOREIGN KEY ("UPLOADHISTORYID") REFERENCES "SHAREDCLOUD"."UPLOAD_HISTORY" ("ID") ON DELETE CASCADE;
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES" ADD FOREIGN KEY ("USERID") REFERENCES "SHAREDCLOUD"."USERS" ("USERID") ON DELETE CASCADE;

-- ----------------------------
-- Foreign Key structure for table "SHAREDCLOUD"."SHAREDFILES_MAG_LOG"
-- ----------------------------
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES_MAG_LOG" ADD FOREIGN KEY ("ADMID") REFERENCES "SHAREDCLOUD"."ADM" ("ADMID");
ALTER TABLE "SHAREDCLOUD"."SHAREDFILES_MAG_LOG" ADD FOREIGN KEY ("SHAREDFILEID") REFERENCES "SHAREDCLOUD"."SHAREDFILES" ("SHAREDFILEID");

-- ----------------------------
-- Foreign Key structure for table "SHAREDCLOUD"."UPLOAD_HISTORY"
-- ----------------------------
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY" ADD FOREIGN KEY ("FILEID") REFERENCES "SHAREDCLOUD"."FILES" ("FILEID") ON DELETE CASCADE;
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY" ADD FOREIGN KEY ("PID") REFERENCES "SHAREDCLOUD"."UPLOAD_HISTORY" ("ID") ON DELETE CASCADE;
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY" ADD FOREIGN KEY ("USERID") REFERENCES "SHAREDCLOUD"."USERS" ("USERID") ON DELETE CASCADE;

-- ----------------------------
-- Foreign Key structure for table "SHAREDCLOUD"."UPLOAD_HISTORY_MAG_LOG"
-- ----------------------------
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY_MAG_LOG" ADD FOREIGN KEY ("ID") REFERENCES "SHAREDCLOUD"."ADM" ("ADMID");
ALTER TABLE "SHAREDCLOUD"."UPLOAD_HISTORY_MAG_LOG" ADD FOREIGN KEY ("ID") REFERENCES "SHAREDCLOUD"."UPLOAD_HISTORY" ("ID");

-- ----------------------------
-- Foreign Key structure for table "SHAREDCLOUD"."UPLOADHISTORY_MAG_LOG"
-- ----------------------------
ALTER TABLE "SHAREDCLOUD"."UPLOADHISTORY_MAG_LOG" ADD FOREIGN KEY ("UPLOAD_HISTORY_ID") REFERENCES "SHAREDCLOUD"."UPLOAD_HISTORY" ("ID");
ALTER TABLE "SHAREDCLOUD"."UPLOADHISTORY_MAG_LOG" ADD FOREIGN KEY ("ADMID") REFERENCES "SHAREDCLOUD"."ADM" ("ADMID");

-- ----------------------------
-- Foreign Key structure for table "SHAREDCLOUD"."USERS_MAG_LOG"
-- ----------------------------
ALTER TABLE "SHAREDCLOUD"."USERS_MAG_LOG" ADD FOREIGN KEY ("ADMID") REFERENCES "SHAREDCLOUD"."ADM" ("ADMID");
ALTER TABLE "SHAREDCLOUD"."USERS_MAG_LOG" ADD FOREIGN KEY ("USERID") REFERENCES "SHAREDCLOUD"."USERS" ("USERID");
